name             'ksApp'
maintainer       'cr0w'
maintainer_email 'ihatenegi@gmail.com'
license          'All rights reserved'
description      'Installs/Configures ksApp'
long_description 'Installs/Configures ksApp'
version          '0.1.0'
